# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Workspace\pyjsa\src\pyjsa\assets\ui\databaseSelector.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DatabaseSelector(object):
    def setupUi(self, DatabaseSelector):
        DatabaseSelector.setObjectName("DatabaseSelector")
        DatabaseSelector.resize(295, 426)
        self.verticalLayout = QtWidgets.QVBoxLayout(DatabaseSelector)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBoxList = QtWidgets.QGroupBox(DatabaseSelector)
        self.groupBoxList.setObjectName("groupBoxList")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBoxList)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listViewDatabase = QtWidgets.QListView(self.groupBoxList)
        self.listViewDatabase.setObjectName("listViewDatabase")
        self.horizontalLayout.addWidget(self.listViewDatabase)
        self.verticalLayout.addWidget(self.groupBoxList)
        self.pushButtonSaveUpdate = QtWidgets.QPushButton(DatabaseSelector)
        self.pushButtonSaveUpdate.setObjectName("pushButtonSaveUpdate")
        self.verticalLayout.addWidget(self.pushButtonSaveUpdate)
        self.pushButtonRetrieve = QtWidgets.QPushButton(DatabaseSelector)
        self.pushButtonRetrieve.setObjectName("pushButtonRetrieve")
        self.verticalLayout.addWidget(self.pushButtonRetrieve)
        self.pushButtonDelete = QtWidgets.QPushButton(DatabaseSelector)
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.verticalLayout.addWidget(self.pushButtonDelete)

        self.retranslateUi(DatabaseSelector)
        QtCore.QMetaObject.connectSlotsByName(DatabaseSelector)

    def retranslateUi(self, DatabaseSelector):
        _translate = QtCore.QCoreApplication.translate
        DatabaseSelector.setWindowTitle(_translate("DatabaseSelector", "Form"))
        self.groupBoxList.setTitle(_translate("DatabaseSelector", "GroupBox"))
        self.pushButtonSaveUpdate.setText(_translate("DatabaseSelector", "Save/Update"))
        self.pushButtonRetrieve.setText(_translate("DatabaseSelector", "Retrieve"))
        self.pushButtonDelete.setText(_translate("DatabaseSelector", "Delete"))
