# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Workspace\pyjsa\src\pyjsa\assets\ui\polingForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PolingForm(object):
    def setupUi(self, PolingForm):
        PolingForm.setObjectName("PolingForm")
        PolingForm.resize(632, 495)
        self.verticalLayout = QtWidgets.QVBoxLayout(PolingForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plotWidgetPoling = PlotWidget(PolingForm)
        self.plotWidgetPoling.setObjectName("plotWidgetPoling")
        self.verticalLayout.addWidget(self.plotWidgetPoling)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(PolingForm)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonRegular = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonRegular.setObjectName("pushButtonRegular")
        self.gridLayout.addWidget(self.pushButtonRegular, 0, 0, 1, 1)
        self.pushButtonGaussian = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonGaussian.setObjectName("pushButtonGaussian")
        self.gridLayout.addWidget(self.pushButtonGaussian, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.doubleSpinBoxLength = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBoxLength.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBoxLength.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBoxLength.setProperty("value", 5.0)
        self.doubleSpinBoxLength.setObjectName("doubleSpinBoxLength")
        self.gridLayout.addWidget(self.doubleSpinBoxLength, 1, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(PolingForm)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButtonFromTPM = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonFromTPM.setObjectName("pushButtonFromTPM")
        self.horizontalLayout_3.addWidget(self.pushButtonFromTPM)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(PolingForm)
        QtCore.QMetaObject.connectSlotsByName(PolingForm)

    def retranslateUi(self, PolingForm):
        _translate = QtCore.QCoreApplication.translate
        PolingForm.setWindowTitle(_translate("PolingForm", "Form"))
        self.groupBox.setTitle(_translate("PolingForm", "From process"))
        self.pushButtonRegular.setText(_translate("PolingForm", "Regular"))
        self.pushButtonGaussian.setText(_translate("PolingForm", "Gaussian"))
        self.label.setText(_translate("PolingForm", "Length"))
        self.doubleSpinBoxLength.setSuffix(_translate("PolingForm", "mm"))
        self.groupBox_2.setTitle(_translate("PolingForm", "External"))
        self.pushButtonFromTPM.setText(_translate("PolingForm", "From TPM"))
from pyqtgraph import PlotWidget
